services:
  - type: web
    name: automate-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: DOMAIN
        value: "https://automate-pro-jqy1.onrender.com"
      - key: CRON_SECRET
        sync: false
